import psutil
from datetime import datetime

LAST_BOOT = datetime.fromtimestamp(psutil.boot_time()).astimezone()

TRIGGER_TYPE_NAME = {
    0: "TASK_TRIGGER_EVENT",
    1: "TASK_TRIGGER_TIME",
    2: "TASK_TRIGGER_DAILY",
    3: "TASK_TRIGGER_WEEKLY",
    4: "TASK_TRIGGER_MONTHLY",
    5: "TASK_TRIGGER_MONTHLYDOW",
    6: "TASK_TRIGGER_IDLE",
    7: "TASK_TRIGGER_REGISTRATION",
    8: "TASK_TRIGGER_BOOT",
    9: "TASK_TRIGGER_LOGON",
    11: "TASK_TRIGGER_SESSION_STATE_CHANGE",
    12: "TASK_TRIGGER_CUSTOM_TRIGGER_01",
    }

error_dict = {
    0x00000000: ("SCHED_S_TASK_SUCCESS", "Task run successfully"),
    0x00041300: ("SCHED_S_TASK_READY", "The task is ready to run at its next scheduled time."),
    0x00041301: ("SCHED_S_TASK_RUNNING", "The task is currently running."),
    0x00041302: ("SCHED_S_TASK_DISABLED", "The task will not run at the scheduled times because it has been disabled."),
    0x00041303: ("SCHED_S_TASK_HAS_NOT_RUN", "The task has not yet run."),
    0x00041304: ("SCHED_S_TASK_NO_MORE_RUNS", "There are no more runs scheduled for this task."),
    0x00041305: ("SCHED_S_TASK_NOT_SCHEDULED", "One or more of the properties that are needed to run this task on a schedule have not been set."),
    0x00041306: ("SCHED_S_TASK_TERMINATED", "The last run of the task was terminated by the user."),
    0x00041308: ("SCHED_S_EVENT_TRIGGER", "Event triggers do not have set run times."),
    0x80041309: ("SCHED_E_TRIGGER_NOT_FOUND", "A task's trigger is not found."),
    0x8004130A: ("SCHED_E_TASK_NOT_READY", "One or more of the properties required to run this task have not been set."),
    0x8004130B: ("SCHED_E_TASK_NOT_RUNNING", "There is no running instance of the task."),
    0x8004130C: ("SCHED_E_SERVICE_NOT_INSTALLED", "The Task Scheduler service is not installed on this computer."),
    0x8004130D: ("SCHED_E_CANNOT_OPEN_TASK", "The task object could not be opened."),
    0x8004130E: ("SCHED_E_INVALID_TASK", "The object is either an invalid task object or is not a task object."),
    0x8004130F: ("SCHED_E_ACCOUNT_INFORMATION_NOT_SET", "No account information could be found in the Task Scheduler security database for the task indicated."),
    0x80041310: ("SCHED_E_ACCOUNT_NAME_NOT_FOUND", "Unable to establish existence of the account specified."),
    0x80041311: ("SCHED_E_ACCOUNT_DBASE_CORRUPT", "Corruption was detected in the Task Scheduler security database; the database has been reset."),
    0x80041312: ("SCHED_E_NO_SECURITY_SERVICES", "Task Scheduler security services are available only on Windows NT."),
    0x80041313: ("SCHED_E_UNKNOWN_OBJECT_VERSION", "The task object version is either unsupported or invalid."),
    0x80041314: ("SCHED_E_UNSUPPORTED_ACCOUNT_OPTION", "The task has been configured with an unsupported combination of account settings and run time options."),
    0x80041315: ("SCHED_E_SERVICE_NOT_RUNNING", "The Task Scheduler Service is not running."),
    0x80041316: ("SCHED_E_UNEXPECTEDNODE", "The task XML contains an unexpected node."),
    0x80041317: ("SCHED_E_NAMESPACE", "The task XML contains an element or attribute from an unexpected namespace."),
    0x80041318: ("SCHED_E_INVALIDVALUE", "The task XML contains a value which is incorrectly formatted or out of range."),
    0x80041319: ("SCHED_E_MISSINGNODE", "The task XML is missing a required element or attribute."),
    0x8004131A: ("SCHED_E_MALFORMEDXML", "The task XML is malformed."),
    0x0004131B: ("SCHED_S_SOME_TRIGGERS_FAILED", "The task is registered, but not all specified triggers will start the task."),
    0x0004131C: ("SCHED_S_BATCH_LOGON_PROBLEM", "The task is registered, but may fail to start. Batch logon privilege needs to be enabled for the task principal."),
    0x8004131D: ("SCHED_E_TOO_MANY_NODES", "The task XML contains too many nodes of the same type."),
    0x8004131E: ("SCHED_E_PAST_END_BOUNDARY", "The task cannot be started after the trigger end boundary."),
    0x8004131F: ("SCHED_E_ALREADY_RUNNING", "An instance of this task is already running."),
    0x80041320: ("SCHED_E_USER_NOT_LOGGED_ON", "The task will not run because the user is not logged on."),
    0x80041321: ("SCHED_E_INVALID_TASK_HASH", "The task image is corrupt or has been tampered with."),
    0x80041322: ("SCHED_E_SERVICE_NOT_AVAILABLE", "The Task Scheduler service is not available."),
    0x80041323: ("SCHED_E_SERVICE_TOO_BUSY", "The Task Scheduler service is too busy to handle your request. Please try again later."),
    0x80041324: ("SCHED_E_TASK_ATTEMPTED", "The Task Scheduler service attempted to run the task, but the task did not run due to one of the constraints in the task definition."),
    0x00041325: ("SCHED_S_TASK_QUEUED", "The Task Scheduler service has asked the task to run."),
    0x80041326: ("SCHED_E_TASK_DISABLED", "The task is disabled."),
    0x80041327: ("SCHED_E_TASK_NOT_V1_COMPAT", "The task has properties that are not compatible with earlier versions of Windows."),
    0x80041328: ("SCHED_E_START_ON_DEMAND", "The task settings do not allow the task to start on demand."),
    }